//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QlyKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIKHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIKHACHHANG()
        {
            this.KHACHHANGs = new HashSet<KHACHHANG>();
        }
    
        public string MaLoaiKhachHang { get; set; }
        public string TenLoaiKhachHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }

        public override string ToString()
        {
            return TenLoaiKhachHang;
        }
    }
}
