//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QlyKhachSan.Model
{
    using System;
    using System.Collections.Generic;

    public partial class PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.PHIEUTHUEs = new HashSet<PHIEUTHUE>();
        }

        public string MaPhong { get; set; }
        public string TenPhong { get; set; }
        public string MaLoaiPhong { get; set; }
        public string GhiChu { get; set; }

        public virtual LOAIPHONG LOAIPHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHUE> PHIEUTHUEs { get; set; }

        public override string ToString()
        {
            return TenPhong;
        }
    }
}
