//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QlyKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public Nullable<int> SoKhachHangToiDa { get; set; }
        public int ID { get; set; }
        public Nullable<bool> QuyDinhPhuThu { get; set; }
        public Nullable<bool> QuyDinhHeSo { get; set; }
        public Nullable<double> TyLePhuThu { get; set; }
    }
}
